### ISSUE TITLE
使用Popup 弹出层d

### ISSUE THREAD

**Issue by Thinker-feiluo** [nutui-uniapp/nutui-uniapp#423]
### nutui-uniapp 版本号

1.7.16

### 平台

h5, 其他小程序

### 重现步骤

![截图20240914154306](https://github.com/user-attachments/assets/5f3511f1-0951-4fc0-bdb2-68e7779cf499)
这两个自定义弹出无法在<style>标签中设置他的样式比如
![image](https://github.com/user-attachments/assets/5ecd951c-e9f9-4f63-adf0-fef37fba4e55)
他无法设置弹出框的高度或者别的属性,在所有的app，h5都无法设置
![image](https://github.com/user-attachments/assets/ffac76bd-d54a-4800-8d18-57d6fb26294f)
但是k可以使用sass选中这个class类下面的class

### 期望的结果是什么？

解决问题

### 实际的结果是什么？

解决问题

### 环境信息

123

### 其他补充信息

123

**Comment by xiaohe0601** [comment]
添加一个 `noscoped` 的 style 块（参考 [issues 4491](https://github.com/dcloudio/uni-app/issues/4491)）

```scss
<style lang="scss" noscoped>
.custom-popup {
  height: 80%;
}
</style>
```
