### ISSUE TITLE
form-item 有个::afer伪元素的下划线，在微信小程序上去不掉的问题

### ISSUE THREAD

**Issue by alicemw** [nutui-uniapp/nutui-uniapp#460]
### nutui-uniapp 版本号

1.8.3

### 平台

weapp

### 重现链接

没有

### 重现步骤

在你的官网上可以看到你的form-item的下划线是一个after伪类元素，但是在微信小程序上，我在他的微信开发者工具上找，根本找不到这样一个带有boder-bottom的伪类元素。这种情况我该怎么把你的 form-item的 下划线给去除掉？

### 期望的结果是什么？

去掉微信小程序中 form-item的下划线

### 实际的结果是什么？

去不掉

**Comment by bihongbin3027** [comment]
官网访问不了了

**Comment by xiaohe0601** [comment]
因为 form-item 嵌套了 cell，所以要修改 cell 的样式，下面是示例：

```html
<template>
  <nut-form custom-class="custom-form">
    <!-- ... -->
  </nut-form>
</template>
```

```scss
.custom-form {
  :deep() {
    .nut-cell {
      &::after {
        display: none;
      }
    }
  }
}
```
